/// <reference types="astro/client" />

/**
 * `Env` is generated by `npm run cf-typegen` (wrangler types) from
 * wrangler.jsonc, and already covers the D1 binding, the static-asset binding
 * and the plain `vars`. Secrets are set with `wrangler secret put` and so never
 * appear in that file — they are declared here instead.
 */
type ENV = Env & {
	/** Resend API key. https://resend.com/api-keys */
	RESEND_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	/** Long random string; signs the OAuth state cookie and salts client-IP hashes. */
	SESSION_SECRET: string;
	/** Comma-separated allowlist of Google accounts permitted into /admin. */
	ADMIN_EMAILS: string;
};

declare namespace App {
	interface Locals {
		/** Injected by @astrojs/cloudflare on every non-prerendered route. */
		runtime: {
			env: ENV;
			cf: unknown;
			ctx: ExecutionContext;
			caches: CacheStorage;
		};
	}
}
